<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Hgv_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get hgv_user by user_id
     */
    function get_hgv_user($user_id)
    {
        return $this->db->get_where('hgv_users',array('user_id'=>$user_id))->row_array();
    }
    
    /*
     * Get all hgv_user
     */
    function get_all_hgv_user()
    {
        return $this->db->get('hgv_users')->result_array();
    }
    
    /*
     * function to add new hgv_user
     */
    function add_hgv_user($params)
    {
        $this->db->insert('hgv_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update hgv_user
     */
    function update_hgv_user($user_id,$params)
    {
        $this->db->where('user_id',$user_id);
        $response = $this->db->update('hgv_users',$params);
        if($response)
        {
            return "hgv_user updated successfully";
        }
        else
        {
            return "Error occuring while updating hgv_user";
        }
    }
    
    /*
     * function to delete hgv_user
     */
    function delete_hgv_user($user_id)
    {
        $response = $this->db->delete('hgv_users',array('user_id'=>$user_id));
        if($response)
        {
            return "hgv_user deleted successfully";
        }
        else
        {
            return "Error occuring while deleting hgv_user";
        }
    }
}